name = input ("First name: ")
name1 = input ("Last name: ")
age = input ("age: ")
print ("Your fullname is", name, name1, "and your age is", age  )
#print (f' ("Your fullname is") {name} {name1} ("and your age is") {age}')