charA = ord('A')
charB = ord('B')
charC = ord('C')
charD = ord('D')
charb = ord('b')
charc = ord('c')
chard = ord('d')
char0 = ord('0')
char1 = ord('1')
char2 = ord('2')
char4 = ord('$')
char5 = ord('*')
char6 = ord('+')
char = ord(' ')

print (charA, charB, charC, charD, charb, charc, chard, char0, char1, char2, char4, char5, char6, char)
